name: Pipeline

permissions:
  packages: write

on:
  push:
    branches:
      - trunk

jobs:
  run:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: docker build -t flaskapp:latest .
      - name: test
        run: echo "Running tests..."
      - name: authenticate with GHCR
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: tag the image
        run: |
          docker tag flaskapp:latest ghcr.io/${{ github.repository }}:latest
      - name: Push to registry
        run: docker push ghcr.io/${{ github.repository }}:latest

